{
 "title": "Consultas API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Promedio – Duración Solicitudes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(demo_api_request_duration_seconds_sum[5m])) by (path, method) / sum(rate(demo_api_request_duration_seconds_count[5m])) by (path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentil 95 – Duración Solicitudes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(demo_api_request_duration_seconds_bucket[5m])) by (le, path, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentil 90 – Duración Solicitudes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(demo_api_request_duration_seconds_bucket[5m])) by (le, path, method))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}